name: argument-graph-builder
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - altair=6.0.0=pyhd8ed1ab_1
  - annotated-types=0.7.0=pyhd8ed1ab_1
  - attrs=25.4.0=pyhcf101f3_1
  - aws-c-auth=0.9.3=hef928c7_0
  - aws-c-cal=0.9.13=h2c9d079_1
  - aws-c-common=0.12.6=hb03c661_0
  - aws-c-compression=0.3.1=h8b1a151_9
  - aws-c-event-stream=0.5.7=h28f887f_1
  - aws-c-http=0.10.7=ha8fc4e3_5
  - aws-c-io=0.23.3=hdaf4b65_5
  - aws-c-mqtt=0.13.3=hc63082f_11
  - aws-c-s3=0.11.3=h06ab39a_1
  - aws-c-sdkutils=0.2.4=h8b1a151_4
  - aws-checksums=0.2.7=h8b1a151_5
  - aws-crt-cpp=0.35.4=h8824e59_0
  - aws-sdk-cpp=1.11.606=h20b40b1_10
  - azure-core-cpp=1.16.1=h3a458e0_0
  - azure-identity-cpp=1.13.2=h3a5f585_1
  - azure-storage-blobs-cpp=12.16.0=h75daedc_0
  - azure-storage-common-cpp=12.12.0=h3d7a050_0
  - azure-storage-files-datalake-cpp=12.14.0=hd454692_0
  - backports.zstd=1.3.0=py310h69bd2ac_0
  - blinker=1.9.0=pyhff2d567_0
  - brotli-python=1.2.0=py310hba01987_1
  - bzip2=1.0.8=hda65f42_8
  - c-ares=1.34.6=hb03c661_0
  - ca-certificates=2026.1.4=hbd8a1cb_0
  - cachetools=6.2.4=pyhd8ed1ab_0
  - cairo=1.18.4=he90730b_1
  - catalogue=2.0.10=py310hff52083_2
  - certifi=2026.1.4=pyhd8ed1ab_0
  - charset-normalizer=3.4.4=pyhd8ed1ab_0
  - click=8.3.1=pyh8f84b5b_1
  - cloudpathlib=0.23.0=pyhd8ed1ab_0
  - cloudpickle=3.1.2=pyhcf101f3_1
  - colorama=0.4.6=pyhd8ed1ab_1
  - confection=0.1.5=pyhecae5ae_0
  - coverage=7.13.2=py310h3406613_0
  - curl=8.18.0=h4e3cde8_0
  - cymem=2.0.13=py310hea6c23e_1
  - cython-blis=1.3.3=py310hf779ad0_0
  - exceptiongroup=1.3.1=pyhd8ed1ab_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h7e30c49_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=hc364b38_1
  - freeglut=3.2.2=ha6d2627_3
  - freetype=2.14.1=ha770c72_0
  - gflags=2.2.2=h5888daf_1005
  - gitdb=4.0.12=pyhd8ed1ab_0
  - gitpython=3.1.46=pyhd8ed1ab_0
  - glog=0.7.1=hbabe93e_0
  - graphite2=1.3.14=hecca717_2
  - h2=4.3.0=pyhcf101f3_0
  - harfbuzz=12.3.2=h6083320_0
  - hpack=4.1.0=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icu=78.2=h33c6efd_0
  - idna=3.11=pyhd8ed1ab_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - iniconfig=2.3.0=pyhd8ed1ab_0
  - jbig2dec=0.18=h267a509_0
  - jinja2=3.1.6=pyhcf101f3_1
  - jsonschema=4.26.0=pyhcf101f3_0
  - jsonschema-specifications=2025.9.1=pyhcf101f3_0
  - keyutils=1.6.3=hb9d3cd8_0
  - krb5=1.21.3=h659f571_0
  - lcms2=2.18=h0c24ade_0
  - ld_impl_linux-64=2.45=default_hbd61a6d_105
  - lerc=4.0.0=h0aef613_1
  - libabseil=20250512.1=cxx17_hba17884_0
  - libarrow=23.0.0=h2c50142_0_cpu
  - libarrow-acero=23.0.0=h635bf11_0_cpu
  - libarrow-compute=23.0.0=h8c2c5c3_0_cpu
  - libarrow-dataset=23.0.0=h635bf11_0_cpu
  - libarrow-substrait=23.0.0=h3f74fd7_0_cpu
  - libblas=3.11.0=5_h4a7cf45_openblas
  - libbrotlicommon=1.2.0=hb03c661_1
  - libbrotlidec=1.2.0=hb03c661_1
  - libbrotlienc=1.2.0=hb03c661_1
  - libcblas=3.11.0=5_h0358290_openblas
  - libcrc32c=1.1.2=h9c3ff4c_0
  - libcurl=8.18.0=h4e3cde8_0
  - libdeflate=1.25=h17f619e_0
  - libedit=3.1.20250104=pl5321h7949ede_0
  - libev=4.33=hd590300_2
  - libevent=2.1.12=hf998b51_1
  - libexpat=2.7.3=hecca717_0
  - libffi=3.5.2=h9ec8514_0
  - libfreetype=2.14.1=ha770c72_0
  - libfreetype6=2.14.1=h73754d4_0
  - libgcc=15.2.0=he0feb66_16
  - libgcc-ng=15.2.0=h69a702a_16
  - libgfortran=15.2.0=h69a702a_16
  - libgfortran5=15.2.0=h68bc16d_16
  - libglib=2.86.3=h6548e54_0
  - libgomp=15.2.0=he0feb66_16
  - libgoogle-cloud=2.39.0=hdb79228_0
  - libgoogle-cloud-storage=2.39.0=hdbdcf42_0
  - libgrpc=1.73.1=h3288cfb_1
  - libgumbo=1.0.0=h3f2d84a_1
  - libiconv=1.18=h3b78370_2
  - libjpeg-turbo=3.1.2=hb03c661_0
  - liblapack=3.11.0=5_h47877c9_openblas
  - liblzma=5.8.2=hb03c661_0
  - libnghttp2=1.67.0=had1ee68_0
  - libnsl=2.0.1=hb9d3cd8_1
  - libopenblas=0.3.30=pthreads_h94d23a6_4
  - libopentelemetry-cpp=1.21.0=hb9b0907_1
  - libopentelemetry-cpp-headers=1.21.0=ha770c72_1
  - libparquet=23.0.0=h7376487_0_cpu
  - libpng=1.6.54=h421ea60_0
  - libprotobuf=6.31.1=h49aed37_4
  - libre2-11=2025.11.05=h7b12aa8_0
  - libsqlite=3.51.2=hf4e2dac_0
  - libssh2=1.11.1=hcf80075_0
  - libstdcxx=15.2.0=h934c35e_16
  - libstdcxx-ng=15.2.0=hdf11a46_16
  - libthrift=0.22.0=h454ac66_1
  - libtiff=4.7.1=h9d88235_1
  - libutf8proc=2.11.3=hfe17d71_0
  - libuuid=2.41.3=h5347b49_0
  - libwebp-base=1.6.0=hd42ef1d_0
  - libxcb=1.17.0=h8a09558_0
  - libxcrypt=4.4.36=hd590300_1
  - libxml2=2.15.1=he237659_1
  - libxml2-16=2.15.1=hca6bf5a_1
  - libzlib=1.3.1=hb9d3cd8_2
  - lz4-c=1.10.0=h5888daf_1
  - markdown-it-py=4.0.0=pyhd8ed1ab_0
  - markupsafe=3.0.3=py310h3406613_0
  - mdurl=0.1.2=pyhd8ed1ab_1
  - mupdf=1.24.1=py310hba70a52_4
  - murmurhash=1.0.15=py310h25320af_1
  - narwhals=2.15.0=pyhcf101f3_0
  - ncurses=6.5=h2d0b736_3
  - nlohmann_json=3.12.0=h54a6638_1
  - numpy=2.2.6=py310hefbff90_0
  - openjpeg=2.5.4=h55fea9a_0
  - openssl=3.6.1=h35e630c_1
  - orc=2.2.2=h19cb568_0
  - pandas=2.3.3=py310h0158d43_2
  - pcre2=10.47=haa7fec5_0
  - pillow=12.1.0=py310h5a73078_0
  - pip=25.3=pyh8b19718_0
  - pixman=0.46.4=h54a6638_1
  - pluggy=1.6.0=pyhf9edf01_1
  - preshed=3.0.12=py310hea6c23e_1
  - prometheus-cpp=1.3.0=ha5d0236_0
  - protobuf=6.31.1=py310ha36e12e_2
  - pthread-stubs=0.4=hb9d3cd8_1002
  - pyarrow=23.0.0=py310hff52083_0
  - pyarrow-core=23.0.0=py310h923f568_0_cpu
  - pydantic=2.12.5=pyhcf101f3_1
  - pydantic-core=2.41.5=py310hd8f68c5_1
  - pydeck=0.9.1=pyhd8ed1ab_0
  - pygments=2.19.2=pyhd8ed1ab_0
  - pymupdf=1.24.1=py310h19a0cbb_0
  - pysocks=1.7.1=pyha55dd90_7
  - pytest=9.0.2=pyhcf101f3_0
  - pytest-cov=7.0.0=pyhcf101f3_1
  - python=3.10.19=h3c07f61_3_cpython
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-tzdata=2025.3=pyhd8ed1ab_0
  - python_abi=3.10=8_cp310
  - pytz=2025.2=pyhd8ed1ab_0
  - pyyaml=6.0.3=py310h3406613_0
  - re2=2025.11.05=h5301d42_0
  - readline=8.3=h853b02a_0
  - referencing=0.37.0=pyhcf101f3_0
  - requests=2.32.5=pyhcf101f3_1
  - rich=14.3.1=pyhcf101f3_0
  - rpds-py=0.30.0=py310hd8f68c5_0
  - s2n=1.6.2=he8a4886_1
  - setuptools=80.10.1=pyh332efcf_0
  - shellingham=1.5.4=pyhd8ed1ab_2
  - six=1.17.0=pyhe01879c_1
  - smart-open=7.5.0=h0f9f196_0
  - smart_open=7.5.0=pyhcf101f3_0
  - smmap=5.0.2=pyhd8ed1ab_0
  - snappy=1.2.2=h03e3b7b_1
  - spacy=3.8.11=py310hc563356_0
  - spacy-legacy=3.0.12=pyhd8ed1ab_0
  - spacy-loggers=1.0.5=pyhd8ed1ab_0
  - srsly=2.5.2=py310hea6c23e_0
  - streamlit=1.53.1=pyhd8ed1ab_0
  - tenacity=9.1.2=pyhd8ed1ab_0
  - thinc=8.3.10=py310hc563356_0
  - tk=8.6.13=noxft_ha0e22de_103
  - toml=0.10.2=pyhcf101f3_3
  - tomli=2.4.0=pyhcf101f3_0
  - tornado=6.5.4=py310ha78b2d2_0
  - tqdm=4.67.1=pyhd8ed1ab_1
  - typer=0.21.1=pyhf8876ea_0
  - typer-slim=0.21.1=pyhcf101f3_0
  - typer-slim-standard=0.21.1=h378290b_0
  - typing-extensions=4.15.0=h396c80c_0
  - typing-inspection=0.4.2=pyhd8ed1ab_1
  - typing_extensions=4.15.0=pyhcf101f3_0
  - tzdata=2025c=hc9c84f9_1
  - ujson=5.11.0=py310h25320af_1
  - urllib3=2.6.3=pyhd8ed1ab_0
  - wasabi=1.1.3=pyhd8ed1ab_1
  - watchdog=6.0.0=py310hff52083_2
  - weasel=0.4.3=pyhd8ed1ab_0
  - wheel=0.46.3=pyhd8ed1ab_0
  - wrapt=2.0.1=py310h7c4b9e2_1
  - xorg-libice=1.1.2=hb9d3cd8_0
  - xorg-libsm=1.2.6=he73a12e_0
  - xorg-libx11=1.8.12=h4f16b4b_0
  - xorg-libxau=1.0.12=hb03c661_1
  - xorg-libxdmcp=1.1.5=hb03c661_1
  - xorg-libxext=1.3.7=hb03c661_0
  - xorg-libxfixes=6.0.2=hb03c661_0
  - xorg-libxi=1.8.2=hb9d3cd8_0
  - xorg-libxrender=0.9.12=hb9d3cd8_0
  - yaml=0.2.5=h280c20c_3
  - zipp=3.23.0=pyhcf101f3_1
  - zlib=1.3.1=hb9d3cd8_2
  - zlib-ng=2.3.2=hceb46e0_1
  - zstd=1.5.7=hb78ec9c_6
  - pip:
      - anyio==4.12.1
      - asttokens==3.0.1
      - decorator==5.2.1
      - distro==1.9.0
      - executing==2.2.1
      - h11==0.16.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - ipython==8.38.0
      - jedi==0.19.2
      - jiter==0.12.0
      - jsonpatch==1.33
      - jsonpickle==4.1.1
      - jsonpointer==3.0.0
      - langchain-core==1.2.7
      - langchain-openai==1.1.7
      - langsmith==0.6.4
      - matplotlib-inline==0.2.1
      - networkx==3.4.2
      - openai==2.15.0
      - orjson==3.11.5
      - packaging==25.0
      - parso==0.8.5
      - pexpect==4.9.0
      - prompt-toolkit==3.0.52
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pyvis==0.3.2
      - regex==2026.1.15
      - requests-toolbelt==1.0.0
      - sniffio==1.3.1
      - stack-data==0.6.3
      - tiktoken==0.12.0
      - traitlets==5.14.3
      - uuid-utils==0.14.0
      - wcwidth==0.4.0
      - zstandard==0.25.0
prefix: /home/eyalk/Apps/anaconda3/envs/argument-graph-builder
